allprojects {
    group = project.findProperty('group_id')
    version = project.findProperty('mod_version')
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.findProperty('java_version') as String))
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = Integer.parseInt(project.findProperty('java_version') as String)
    }
}
