org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

# Coordinates
group_id=gg.literal
mod_id=jumpboostbar
mod_name=JumpBoostBar
mod_version=1.1-mcx
java_version=21

# Shared target Minecraft version (override with -Pmc_version=...)
mc_version=1.21.1

# Fabric
loom_version=1.7-SNAPSHOT
fabric_loader_version=0.16.10
fabric_api_version=0.110.0+1.21.1

# NeoForge
neo_moddev_version=2.0.74
neoforge_version=21.1.122

# Paper
paper_api_version=1.21.1-R0.1-SNAPSHOT
shadow_version=8.1.1

# Useful mappings to track when targeting a different MC patch
# 1) fabric_api_version must match mc_version
# 2) neoforge_version must match mc_version branch
# 3) paper_api_version must match mc_version
