modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="literal"
description='''
Because who needs to build leg muscles when you can just... charge up and fly? It's not lazy, it's efficient.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.0,)"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,27)"
